logLevel: debug
extraArgs:
  - --cloudflare-proxied
  # Don't want wildcard DNS records when creating wildcard SSL certs
  - --ignore-ingress-tls-spec

provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cf-dns-api-token
        key: api-token
  - name: GOMEMLIMIT
    value: 120MiB

sources:
  - crd
  - pod
  - service
  - ingress
  - traefik-proxy
  - gateway-httproute

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
