[tools]
kubectl = "1.34.1"
"aqua:sarub0b0/kubetui" = "1.7.1"
kustomize = "5.6.0"
age = "1.2.1"
sops = "3.11.0"
talosctl = "1.11.3"
"ubi:cozystack/talm" = "0.16.2"
cosign = "3.0.2"
watchexec = "2.3.2"
cilium-cli = "0.18.8"
etcd = "3.5.24"
yq = "4.45.4"
"pipx:b2" = "4.4.2"
bun = "1.3.1"
"npm:@karakeep/cli" = "latest"
jj = "0.35.0"
cilium-hubble = "1.18.3"
"aqua:cloudnative-pg/cloudnative-pg/kubectl-cnpg" = "1.27.1"
ripsecrets = "0.1.11"
pre-commit = "4.4.0"

[env]
'_'.file = ["{{config_root}}/.env"]
'_'.path = ["{{config_root}}/bin"]

REPO_ROOT = "{{config_root}}"
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"

[settings]
npm.bun = true

[tasks.b2]
run = "docker run --rm -it -e B2_APPLICATION_KEY -e B2_APPLICATION_KEY_ID backblazeit/b2:4.4.2"
