[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication -force
  s3.clean.uploads -timeAgo=24h
  volume.tier.upload -dest s3 -fullPercent=95 -quietFor=1h
  unlock
"""
sleep_minutes = 17 # sleep minutes between each script execution


# configurations for tiered cloud storage
# old volumes are transparently moved to cloud for cost efficiency
[storage.backend]
[storage.backend.s3.default]
enabled = true
region = "eu-central-003"
bucket = "weedfs"
endpoint = "s3.eu-central-003.backblazeb2.com"
storage_class = "STANDARD_IA"
