apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: gitea
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-star-theta.sophons.cloud
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-vrtx-sh-tls
  routes:
    - kind: Rule
      match: Host(`tig.vrtx.sh`)
      services:
        - kind: Service
          name: gitea-http
          port: 3000
