apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: gitea
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-star-theta.sophons.cloud
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-vrtx-sh-tls
  routes:
    - kind: Rule
      match: Host(`tig.vrtx.sh`)
      services:
        - kind: Service
          name: gitea-http
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-pkg
  namespace: gitea
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-noproxy.sophons.cloud
    external-dns.alpha.kubernetes.io/cloudflare-proxied: false
spec:
  entryPoints:
    - websecure
  tls:
    secretName: pkg-tig-vrtx-sh-tls
  routes:
    - kind: Rule
      match: Host(`pkg.tig.vrtx.sh`)
      services:
        - kind: Service
          name: gitea-http
          port: 3000
