namespace: gitea
resources:
  - httproute.yaml
  - certificate.yaml
  - dnsendpoint.yaml
  - statefulset.yaml
  - secret.sops.yaml

configMapGenerator:
  - name: litestream
    options:
      disableNameSuffixHash: true
    files:
      - config/litestream.yaml
  - name: gitea-runner
    options:
      disableNameSuffixHash: true
    files:
      - config/act_runner.yaml
