apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
  annotations:
    metallb.io/address-pool: starlink
    external-dns.alpha.kubernetes.io/hostname: ssh.tig.vrtx.sh
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: gitea-starlink
  namespace: gitea
spec:
  type: LoadBalancer
  ipFamilies: ["IPv6"]
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 2222
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
  annotations:
    metallb.io/address-pool: theta
    external-dns.alpha.kubernetes.io/hostname: ssh.tig.vrtx.sh
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: gitea-theta
  namespace: gitea
spec:
  type: LoadBalancer
  ipFamilies: ["IPv6"]
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 2222
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea
