namespace: pihole
labels:
  - pairs:
      app.kubernetes.io/name: pihole
    includeSelectors: true
    includeTemplates: true

resources:
  - role.yaml
  - service.yaml
  - rolebinding.yaml
  - statefulset.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: pihole
    files:
      - config/adlists.list
      - config/blacklist.txt
