# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/service.json
apiVersion: v1
kind: Service
metadata:
  name: necronomicon-cluster-dns
  namespace: pihole
spec:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app.kubernetes.io/instance: necronomicon
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/service.json
apiVersion: v1
kind: Service
metadata:
  name: darkhold-0-dns
  namespace: pihole
  annotations:
    metallb.io/address-pool: internal
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app.kubernetes.io/instance: darkhold
    statefulset.kubernetes.io/pod-name: darkhold-0
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/service.json
apiVersion: v1
kind: Service
metadata:
  name: darkhold-1-dns
  namespace: pihole
  annotations:
    metallb.io/address-pool: internal
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app.kubernetes.io/instance: darkhold
    statefulset.kubernetes.io/pod-name: darkhold-1
