apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: goldpinger
    app.kubernetes.io/name: goldpinger
  annotations:
    metallb.io/address-pool: internal
  name: goldpinger-internal
  namespace: goldpinger
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: goldpinger
    app.kubernetes.io/name: goldpinger
