tolerations:
  - key: ""
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
  - key: orunmila.sophons.cloud/ase-orun
    operator: Exists
  - key: prime.sophons.cloud
    operator: Exists

extraEnv:
  - name: PING_TIMEOUT
    value: 500ms
  - name: GOMEMLIMIT
    value: 30MiB
  - name: GOGC
    value: "50"

priorityClassName: system-node-critical

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    memory: 32Mi
