apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pds
  namespace: bluesky
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-star-theta.sophons.cloud
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-vrtx-sh-tls
  routes:
    - kind: Rule
      match: Host(`pds.vrtx.sh`)
      services:
        - kind: Service
          name: bluesky-pds
          port: 3000
    - kind: Rule
      match: Host(`bsky.vrtx.sh`)
      services: []
      middlewares:
        - name: redirect-to-bsky-app
