namespace: authelia
resources:
  - httproute.yaml
  - secret.sops.yaml
  - dnsendpoint.yaml

configMapGenerator:
  - name: authelia-users
    options:
      disableNameSuffixHash: true
    files:
      - users.yaml=config/users.sops.yaml
  - name: litestream
    options:
      disableNameSuffixHash: true
    files:
      - config/litestream.yaml
