defaultBackupStore:
  backupTarget: s3://sophons-longhorn-backup@eu-central-003/
  backupTargetCredentialSecret: backblaze-creds
  pollInterval: "900"

persistence:
  defaultClass: false

defaultSettings:
  systemManagedComponentsNodeSelector: "hugeloads.sophons.cloud/longhorn:true"

longhornManager:
  nodeSelector:
    hugeloads.sophons.cloud/longhorn: "true"

longhornDriver:
  nodeSelector:
    hugeloads.sophons.cloud/longhorn: "true"
  tolerations:
    - key: prime.sophons.cloud
      operator: Exists
