global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "master:9324"
          - "volume:9325"
          - "localhost:9326"
          - "localhost:9327"
          - "litestream:9090"
          - "localhost:9002"
          - "localhost:9090"
