apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: karakeep
  namespace: karakeep
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-star-theta.sophons.cloud
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://holding.sophons.cloud"
    gethomepage.dev/description: Hoard all the things!
    gethomepage.dev/group: Second brain
    gethomepage.dev/icon: karakeep.png
    gethomepage.dev/name: Karakeep
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-sophons-cloud-tls
  routes:
    - kind: Rule
      match: Host(`holding.sophons.cloud`)
      services:
        - kind: Service
          name: karakeep
          port: 3000
