namespace: karakeep
resources:
  - ingress.yaml
  - service.yaml
  - namespace.yaml
  - secret.sops.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: litestream
    options:
      disableNameSuffixHash: true
    files:
      - config/litestream.yaml
