namespace: karakeep
resources:
  - httproute.yaml
  - secret.sops.yaml
  - dnsendpoint.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: litestream
    options:
      disableNameSuffixHash: true
    files:
      - config/litestream.yaml
