# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1/service.json
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/component: karakeep
  annotations:
    metallb.io/address-pool: internal
  name: karakeep-internal
  namespace: karakeep
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/component: karakeep
