apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-star-theta.sophons.cloud
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-sophons-cloud-tls
  routes:
    - kind: Rule
      match: Host(`home.sophons.cloud`)
      services:
        - kind: Service
          name: homepage
          port: 3000
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
