# Required configuration item
providerRegex: ^sophons-.+$
providerIpPrefixes:
  - 10.69.0.0/16
  - 10.42.0.0/16
  # enc!
  - ENC[AES256_GCM,data:ni3Zr2pRm5aYomAuKBnN+MBSNBxa88o=,iv:LaScvCbovAU8w01sURzaafj8kVrX+yE5R7/DQXgInMI=,tag:Xp5K2bpxWRDlTIIJJzp3uQ==,type:str]
  # enc!
  - ENC[AES256_GCM,data:nI0ZJjLLJTLVH5jcX1c=,iv:4eim9FRPoBCm/OFnl2cYiO11n4loffwNHhYBfQsOnwM=,tag:MguPFgyipqoYELnmJEiOSw==,type:str]
  # enc!
  - ENC[AES256_GCM,data:TVu9jubzG5RPNkYZwJPUVqYPFaYw6w==,iv:Wcv/yWUt9agz3Da2EYSuT8hfZKIMUKMCblumIxrqVjM=,tag:cZWSNH7J0J9cbCE7upeUdw==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBTV0w0
        aDk2eXJZREFIeWRhQzlaMGJkK0hvbUtodmtTelJ1T24xY21DemlJClVZdTA5SEZM
        OEd4MTNRTUk4Qk55TWYrZWE1VjJ5MWJhQ2RFSjdaTjlOUk0KLS0tIFowSVZhaTJm
        bHNjejA5SzFYVG0xVG44cGYvKzY3TEtGeERIVDYyMVFLZDQKOZvLHMfkKS0BQ8Vz
        dpAxtgg3CuEql/uL7wJPfNaIwqsSB+kcx2tQSrNqeYFZBTfK7JXzFYcuUOuV2FPf
        ZO3xuA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb01uMFhMK29Yb3Z5UHUr
        bmNJd3JiVFgxVnpBSXF6UkVaYm5GeW04c2g4CmRYUmRUK1NWejJiZENxdmJmdGhO
        YmF3OVZ1eWRiTzdRQ1BGekcvSXhrOTgKLS0tIHBHRzltelJpWWlPTlZFWUFNMll3
        R2NVdUYrOENRcjlnS1hoQkpOREo0V3cKDOYYppO36mHQZcRLU60ufu7yXM3o8MBI
        IDMKOuLs+cv6izLDPYj/+CDfn8xr/q5BtOUoEbeMLc8ZD9vVJ2gXBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T05:06:31Z"
  mac: ENC[AES256_GCM,data:x6OCmogDztxPdC5xqs6/bHye+sshNnxr2JZpG4LXkME6CnYKm5jYDwoBrx8VXuUshBIceEj8QIegi70A5EfVdBO3fufuidZVi6mRedhsubiXxpo0klhT1Eu8uklHD8PUV8S5CJCFhvFW7Cj9HMV6ikXyVbWkPjldGMADaNysU0U=,iv:1kN5jTz+eMLOfouBORJFMvyfuWEnM9QToyTH7cJPcFc=,tag:w/fuAKHNuISkzLqdloPCyQ==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
