apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik-sango-star-theta.sophons.cloud
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://ntfy.sophons.cloud"
    gethomepage.dev/description: Push notifications
    gethomepage.dev/group: Alerting & Notifications
    gethomepage.dev/icon: ntfy.png
    gethomepage.dev/name: Ntfy
spec:
  entryPoints:
    - websecure
  tls:
    secretName: wildcard-sophons-cloud-tls
  routes:
    - kind: Rule
      match: Host(`ntfy.sophons.cloud`)
      services:
        - kind: Service
          name: ntfy
          port: 80
