namespace: ntfy
resources:
  - service.yaml
  - httproute.yaml
  - deployment.yaml
  - secret.sops.yaml
  - dnsendpoint.yaml

configMapGenerator:
  - name: litestream
    files:
      - config/litestream.yaml
      - config/litestream-legacy.yaml

secretGenerator:
  - name: ntfy-config
    files:
      - server.yaml=config/server.sops.yaml
