namespace: ntfy
resources:
  - service.yaml
  - namespace.yaml
  - deployment.yaml
  - secret.sops.yaml
  - ingressroute.yaml

configMapGenerator:
  - name: litestream
    options:
      disableNameSuffixHash: true
    files:
      - config/litestream.yaml
  - name: ntfy
    options:
      disableNameSuffixHash: true
    files:
      - server.yaml=config/server.sops.yaml
