apiVersion: v1
kind: Service
metadata:
  name: ntfy-internal
  namespace: ntfy
  annotations:
    metallb.io/address-pool: internal
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ntfy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
