# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/v1.34.1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: traefik
type: Opaque
stringData:
  # enc!
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/ys25tAjjneC1RV2yC6bb2kcaA2gKanrqFzsg58VoLZB0FIOmzWrPG96dXcOwW1vydYU2Vva2hbWlQDUadoKlY4GONaY3HdsLmAFc6ADR38sw/imRaKfJpLcQm2MCy5+W8IgiCGyhngZcGch10SUV6BOWiLi2qT+TRvz6NT0gTbHnwLFipFNAo5P17YSODnKL7EguL1XT7EjHMEF+KeCzKx2UtR62rPrnp65sGlOJ6LrBGs2ZbPtgA==,iv:oWlvuIxZqYTb366IK0tBuSzjstDXe8jE8HpwuPjn63E=,tag:HJ431tl7qbkQweiyyp+kGg==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII7yyj/sVuDdc6kGEeipVtC0EBaeACTFWHZ9MH77XsFq vrtx@kaos
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNEQlRBdyBodmRN
        b0F1WlJYbllnZGY5NUNDc0FOckxOV0xCdVU5anJUU1BHTGdZZWhNCmdtQzZ0bWVZ
        Zk5icHdFNHJQVUJNT01pWDlFTTgwK0NqdTl4ejNRMjBkWkEKLS0tIFBDWHpuUEpF
        Y1FncTlqeUlZQThXSDZCNEhBMjBUV25RTTB4UjEwMVNFencKfRNlem+2PR/FQVYo
        2smH5MiOUecIwSY8WkLDpEgVw+Eq5N8QSLFmMmREm6HdxCmE+NSThj+dBStAnBJV
        tXcZDw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kum4z0unkunza7kxt4ma7v8k38ggvtjhx6wntnjt8clt6xpyu3eqsw435t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBalc0ZzRzekVMSDVoODZp
        Z3FTVUQ1L3orVm1UZklOTGllWlhGUzRxSVNzCnU5YVpBL2FNbnZNaVFhOVJ2dzJ5
        dDY3L3diZ1k1SzFvSTlKVVUvRHlMeUkKLS0tIFhzSmhJSzkxWkIvN1Y5VlhyZnV0
        VWgvS0J5cUxmeFRLUm9yeVVibGNRc2cKV4bcRXfzJpmS5Dmty+3zE4/r7nfEWSEn
        4gAjHiTxQdjWgYQWPPiIf9b5OtQY+yssJWTvFgegTH1ORAMEKzlP+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T13:28:08Z"
  mac: ENC[AES256_GCM,data:boytqyNVAAQAYcGINmvO+AAoBFKpZRryvXIl0dkuZmDRHq+UUe3GAq4lO1kXNunr1/n5lvXvGguqnTIOfxOBE0l8vj3/sI1vw17Xu+8KolzC9fL6gZoz6vMU/spxiaaqjikNns+Q/QmoAZ00NKGrxovaNQLH5P5M2KhHhSKM/ms=,iv:Tv9JoopB91vfQ2XsfINpzJAwAd2MXLbe3gt4zz0IQ+c=,tag:RsHbfAs79JqIjk08L7t8Yw==,type:str]
  encrypted_comment_regex: enc!
  version: 3.11.0
